# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-a7bb5d36-d4b1-43fd-84dd-bd43f1ffa194";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a7bb5d36-d4b1-43fd-84dd-bd43f1ffa194".device = "/dev/disk/by-uuid/a7bb5d36-d4b1-43fd-84dd-bd43f1ffa194";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3502-F2A4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
